### PR TITLE
[breaking] Sync cassandra-env.sh and jvm.options with Cassandra 3

### PR DESCRIPTION
**Pull request by wdauchy**
tested on both cassandra 2.1.x and 3.x

### CODE REVIEW

**Comment by michaelklishin** [comment]
Noted. Since the title says it includes breaking changes (and yes, some defaults indeed change), let's wait for 4.3.0 before merging this.

**Comment by michaelklishin** [comment]
@wdauchy @jfwm2 speaking of `4.3.0`, I can release it as soon as you folks confirm that master is in good enough shape for you to run it in production ;)

**Comment by wdauchy** [comment]
@michaelklishin this commit is in production on our side for a few months now (september). so in my opinion it is ok.

I however could not find a solution to fix tests; might need new eyes... any hint?

**Comment by michaelklishin** [comment]
@wdauchy I understand that but there is no shortage of other changes in master. They may or may not be in your deployed fork: I cannot know that and thus clarifying.

**Comment by michaelklishin** [comment]
I will take a look at the tests. `chef-spec` doesn't produce diffs so it has to be done by hand :(

**Comment by wdauchy** [comment]
@michaelklishin yup hard to cover all possible configurations; a merge several times before an official release will probably facilitate tests for people

**Comment by wdauchy** [comment]
@michaelklishin we are now good on tests side

**Comment by michaelklishin** [comment]
@wdauchy ack. I will proceed with the `4.3.0` release then.

**Comment by michaelklishin** [comment]
`4.3.0` is out, let's wait for a few days and unless there's urgent need to do a point release, merge this.

**Comment by wdauchy** [comment]
agreed :+1:

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
