### PR TITLE
Add cassandra version 3.11.2

### PR DESCRIPTION
**Pull request by yanivmn**
Cassandra 3.11.2 is required since 3.11.1 has a critical java 8 bug.

### CODE REVIEW

**Comment by yanivmn** [comment]
@michaelklishin - Any chance you can accept this PR today?

**Comment by yanivmn** [comment]
@michaelklishin ?

**Comment by yanivmn** [comment]
@michaelklishin - Any updates ?

**Comment by michaelklishin** [comment]
@yanivmn would you like me to add you as a collaborator so you can quickly push small changes like this one without waiting for me?

**Comment by yanivmn** [comment]
Yes please.

**Comment by michaelklishin** [comment]
@yanivmn done, you should get an invite.

**Pull request merged**
