### PR TITLE
Remove some static values in debian init script and tarball.rb recipe

### PR DESCRIPTION
**Pull request by GennadySpb**

### CODE REVIEW

**Comment by vkhatri** [comment]
is it me or line 189 in `recipes/tarball.rb` should is highlighted as a change. i can see ulimit is already using node attribute for user reference.

screen shot 2015-02-14 at 8 24 35 am

PR looks good.

**Comment by michaelklishin** [comment]
@vkhatri perhaps it was created against an earlier commit (but still can merge cleanly).

**Comment by michaelklishin** [comment]
@GennadySpb thank you.

**Comment by vkhatri** [comment]
@michaelklishin thought so, thanks!

**Pull request merged**
