### PR TITLE
Make the systemd service restart condition configurable via a node attribute

### PR DESCRIPTION
**Pull request by vdemonchy**
This is the follow-up of PR #342

### CODE REVIEW

**Comment by rhardouin** [comment]
I have other things to add in `cassandra.service.erb`. 
Maybe we could create a file `attributes/systemd.rb` and use a naming convention like `default['cassandra']['systemd']['restart_condition']`?

**Comment by michaelklishin** [comment]
@rhardouin I like the idea.

**Comment by rhardouin** [comment]
@vdemonchy we must use bracket notation to be future proof, please see https://github.com/michaelklishin/cassandra-chef-cookbook/issues/345

**Comment by vdemonchy** [comment]
@rhardouin agreed for both suggestions, I'll update my PR !

**Comment by rhardouin** [comment]
LGTM

**Comment by michaelklishin** [comment]
Thank you, @rhardouin and @vdemonchy.

**Pull request merged**
