### PR TITLE
#208, jamm lib is always added in cassandra-env.sh

### PR DESCRIPTION
**Pull request by vkhatri**

### CODE REVIEW

**Comment by vkhatri** [comment]
@michaelklishin looks like in recent or 2.1.x releases, `setup_jamm` is obsolete. unelss we want to disable it completely and not just manage the installtion.

**Comment by michaelklishin** [comment]
The tarball recipe doesn't include the new `config`, at least explicitly. Is this intentional?

**Comment by vkhatri** [comment]
recipe `config` is only included to recipe `default`. now both the recipes are only meant to install C*. like recipe `config`, recipe `java` is now included in recipe `default`.

i did not think of it earlier, but this breaks the setup for existing users. i like this new pattern as we have common attributes present in recipe `default`, so just including `recipe[tarball]` or `recipe[datastax]` should not be enough to complete the setup - even for the existing users.

let me know what do you think about it, i will update `README` accordingly once this PR is merged.

**Comment by michaelklishin** [comment]
@vkhatri this sounds reasonable. Why not update the README up this branch?

**Comment by vkhatri** [comment]
@michaelklishin updated README.

**Comment by michaelklishin** [comment]
:+1:

**Pull request merged**
