### PR TITLE
some additions to testing and initial support for 3.0.0

### PR DESCRIPTION
**Pull request by TD-4242**
You can use docker to run faster kitchen tests by running
```
export KI_DRIVER=docker
```

Also fixed a few minor bugs.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@vkhatri I took the liberty to merge this even though the setup took me an hour and some downloads currently timeout, so I *could* miss something. Feel free to check after me.

@TD-4242 thanks, this is a substantial amount of work. It was fairly difficult to install all the gem dependencies on OS X. Can we simplify the setup somehow?

**Comment by TD-4242** [comment]
I'm not sure, I don't use OSX so don't have a way to even test.  Was it the install of kitchen-docker?  or the docker setup itself?

**Comment by michaelklishin** [comment]
I used Vagrant. It's the dependencies with native code, e.g. Nokogiri, that were most problematic. Moreover, our Gemfile.lock is gigantic: we have probably close to 100 dependencies. Is it really what we need to run integration tests?

**Comment by TD-4242** [comment]
I get them all through the Chef-DK package.  It includes almost everything except a couple of docker dependencies in an omnibus package.

**Pull request merged**
