### PR TITLE
Cleanup testing and deprecations

### PR DESCRIPTION
**Pull request by shortdudey123**

### CODE REVIEW

**Comment by michaelklishin** [comment]
Thanks. Some of the changes go beyond deprecations and "cleanup".

**Comment by michaelklishin** [comment]
I don't mean to criticize but it's the worst kind of pull request a maintainer can receive. It provides no description, no justification of the changes, involves all kinds of unrelated changes, makes claims of "cleaning things up" while changing things that are a matter of personal preference, and assumes that using the latest and greatest (e.g. CentOS 7.0) is the right thing to do.

**Comment by shortdudey123** [comment]
> It provides no description, no justification of the changes

See the commit history :)

**Comment by michaelklishin** [comment]
@shortdudey123 yeah, right. The good old "see commit history, no further explanation necessary" argument. Sorry but it's deeply flawed. Unless you previously had a conversation with the maintainer, providing a brief overview of your changes saves them time and mental energy.

To be fair some of your commits do provide code metrics so it's more useful than average. Let's not get into this because the PR is merged. Thanks for contributing.

**Comment by shortdudey123** [comment]
Most maintainers read the commit history but i will make sure to cover the changes in the description of PRs for your cookbooks in the future.  Sorry about that!

Also, one thought is to add a [PR template](https://github.com/blog/2111-issue-and-pull-request-templates)

**Pull request merged**
