### PR TITLE
Add a restart on-failure condition in systemd service unit

### PR DESCRIPTION
**Pull request by vdemonchy**

### CODE REVIEW

**Comment by michaelklishin** [comment]
I guess this is a good default but there are cases where Cassandra intentionally shuts down (e.g. when it detects disk operation failures and assumes the disk is dysfunctional). So I expect this to become configurable one day.

**Comment by vdemonchy** [comment]
Hello and thanks for the quick merge! You make a point indeed, I guess intentional shutdown for failure cases should result in a unclean exit code and but a clean signal, so on-abnormal would probably be a good fit if so.

**Comment by michaelklishin** [comment]
@vdemonchy agreed. Ideally we should configure the value via a node attribute.

**Comment by vdemonchy** [comment]
Ok, so I'll test that and come back with another PR

**Comment by michaelklishin** [comment]
@vdemonchy thank you!

**Pull request merged**
