### PR TITLE
Allow to upgrade opscenter server

### PR DESCRIPTION
**Pull request by kamaradclimber**

### CODE REVIEW

**Comment by sethrosenblum** [comment]
I think opscenter gets somewhat unhappy when the datastax-agent version is different from the opscenter version.  Those should probably be controlled by the same attribute.

**Comment by michaelklishin** [comment]
I agree with @sethrosenblum.

**Comment by kamaradclimber** [comment]
@michaelklishin  I just uploaded a new patch but I feel it will generate issues later: packages are different and may have different release version (on redhat: 5.1.1-1). I would prefer to have different attributes, what do you think?

**Comment by michaelklishin** [comment]
@kamaradclimber I'd start with this and see what the users say. Thank you.

**Pull request merged**
