### PR TITLE
Improved tests, allow version to properly set attributes, bugfixes

### PR DESCRIPTION
**Pull request by chrishenry**
The changes in this PR include;
* Integrate yum options flag opscenter agent and server
* Improved tests
  * More server spec tests
  * Foodcritic seems to be incorrectly complaining on the user recipe, which is a bit odd.
  * Moved to chef zero, which is faster & allows `search` to be called.
  * chefspec is now successful. (correct? maaaayyybe…)
  * Remove the Chef::config[:solo] from agent recipe., as it makes integration testing super hard.
  * Mock the search in chefspec, and just set the IP attribute in kitchen, which allows for runs in both unit and integration testing.
* Move version switch in attribute to recipe. This allows it to be overridden.
* Specifying a package version on ubuntu simply doesn’t work. This seems to be an issue with with the actual packages.
* C* still doesn’t start on most OSes
 * On cent, it's bc of an old java version.
 * ubuntu bc of a jamm error. `java.lang.NoSuchMethodError: org.github.jamm.MemoryMeter.ignoreKnownSingletons()Lorg/github/jamm/MemoryMeter;`
* Checksums were fixed

### CODE REVIEW

**Comment by vkhatri** [comment]
@chrishenry could you please look into the conflict? changes looks good.

**Comment by chrishenry** [comment]
@vkhatri all set, sorry about that.

**Comment by sethrosenblum** [comment]
The FC048 issue is actually a result of acrmp/foodcritic#252

The fix should be in the next release of foodcritic.

**Comment by michaelklishin** [comment]
Thanks @chrishenry, @vkhatri and @sethrosenblum!

**Pull request merged**
