### PR TITLE
Additional apache cassandra versions (3.10, 3.11.1)

### PR DESCRIPTION
**Pull request by yanivmn**

### CODE REVIEW

**Comment by yanivmn** [comment]
@michaelklishin - can you approve this PR?

**Comment by vkhatri** [comment]
LGTM

Merging.

**Comment by vkhatri** [comment]
@yanivmn 👍

**Comment by yanivmn** [comment]
Thanks

**Comment by michaelklishin** [comment]
Thanks, @vkhatri.

**Pull request merged**
