### PR TITLE
RFC: put all template values into attributes

### PR DESCRIPTION
**Pull request by vkhatri**

### CODE REVIEW

**Comment by michaelklishin** [comment]
Again, my bad for pulling it but it breaks seemingly every installation out there by changing node attribute nesting. This was not reflected in the change log.

**Comment by vkhatri** [comment]
@michaelklishin ok, i got the desired result for rendering `cassandra.yaml` templates using node attributes. i am sorry if it created more issues than solving one. is this not working as intended in the PR or it simply breaks the setup for existing users (which i guess was intended and known) and we need to revert back to the older model?

**Comment by michaelklishin** [comment]
@vkhatri I think the new attribute structure makes more sense but it was a breaking change we should document. I've bumped the version to 4.0.

**Comment by vkhatri** [comment]
@michaelklishin ah! my bad. i remember you mentioned it, but i missed it. thank you for fixing it for me!

**Pull request merged**
