### PR TITLE
Use vnodes as a binary switch; set default num_tokens

### PR DESCRIPTION
**Pull request by vervas**
vnodes attribute should be a binary operator. Set to true by default
since this is a recommended setting.
Define separate attribute for num_tokens and set to the recommended
default of 256.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Can you please provide a proof that DataStax recommends enabling vnodes? If so, I'm happy to change the default.

**Comment by vervas** [comment]
Check the following:
http://www.datastax.com/dev/blog/virtual-nodes-in-cassandra-1-2
http://docs.datastax.com/en/cassandra/2.0/cassandra/architecture/architectureDataDistributeVnodesUsing_c.html

This change however could break pre 1.2 setups. In this case I consider the setting those attributes in the datastax recipe like this:
```
if Gem::Version.new(node['cassandra']['version']) > Gem::Version.new('1.2.0')
  node.default['cassandra']['vnodes'] = true
  node.default['cassandra']['num_tokens'] = 256
end
```

In this case I would revert the default attributes to what it was.

**Comment by michaelklishin** [comment]
Yes, I understand what vnodes do and their benefits. I just haven't see it being an explicit recommendation but it is [Cassandra's own default](https://github.com/apache/cassandra/blob/trunk/conf/cassandra.yaml#L25) these days.

I think we can ignore pre-1.2 versions.

**Comment by michaelklishin** [comment]
Thank you!

**Pull request merged**
