### PR TITLE
Changed log_config_files and jamm related attibutes to be defined at …

### LINKED ISSUE #184: Missing node['cassandra']['log_config_files']
Hi,
I getting the following error:
```
==> Node1: [2015-03-28T14:33:52+00:00] DEBUG: filtered backtrace of compile error: /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:132:in `from_file'
==> Node1: [2015-03-28T14:33:52+00:00] DEBUG: filtered backtrace of compile error: /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:132:in `from_file'
==> Node1: [2015-03-28T14:33:52+00:00] DEBUG: backtrace entry for compile error: '/tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:132:in `from_file''
==> Node1: [2015-03-28T14:33:52+00:00] DEBUG: Line number of compile error: '132'
==> Node1:
==> Node1: ================================================================================
==> Node1: Recipe Compile Error in /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb
==> Node1: ================================================================================
==> Node1:
==> Node1:
==> Node1: NoMethodError
==> Node1: -------------
==> Node1: undefined method `each' for nil:NilClass
==> Node1:
==> Node1:
==> Node1: Cookbook Trace:
==> Node1:
==> Node1: ---------------
==> Node1:   /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:132:in `from_file'
==> Node1:
==> Node1: Relevant File Content:
==> Node1: ----------------------
==> Node1: /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:
==> Node1:
==> Node1: 125:      owner node['cassandra']['user']
==> Node1: 126:      group node['cassandra']['group']
==> Node1: 127:      mode 0644
==> Node1: 128:      notifies :restart, 'service[cassandra]', :delayed if node['cassandra']['notify_restart']
==> Node1: 129:    end
==> Node1: 130:  end
==> Node1: 131:
==> Node1: 132>> node['cassandra']['log_config_files'].each do |f|
==> Node1: 133:    template ::File.join(node['cassandra']['conf_dir'], f) do
==> Node1: 134:      cookbook node['cassandra']['templates_cookbook']
==> Node1: 135:      source "#{f}.erb"
==> Node1: 136:      owner node['cassandra']['user']
==> Node1: 137:      group node['cassandra']['group']
==> Node1: 138:      mode '0644'
==> Node1: 139:      notifies :restart, 'service[cassandra]', :delayed if node['cassandra']['notify_restart']
==> Node1: 140:    end
==> Node1: 141:  end
==> Node1:
==> Node1: [2015-03-28T14:33:52+00:00] DEBUG: Re-raising exception: NoMethodError - undefined method `each' for nil:NilClass
==> Node1: /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:132:in `from_file'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:218:in `load_recipe'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:96:in `load'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/client.rb:249:in `setup_run_context'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/client.rb:446:in `run'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:275:in `block in interval_run_chef_client'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `loop'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `interval_run_chef_client'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:242:in `run_application'
==> Node1:   /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
==> Node1:   /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
==> Node1:   /usr/bin/chef-solo:52:in `load'
==> Node1:   /usr/bin/chef-solo:52:in `<main>'
==> Node1: [2015-03-28T14:33:52+00:00] ERROR: Running exception handlers
==> Node1: [2015-03-28T14:33:52+00:00] ERROR: Exception handlers complete
==> Node1: [2015-03-28T14:33:52+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> Node1: [2015-03-28T14:33:52+00:00] DEBUG: NoMethodError: undefined method `each' for nil:NilClass
==> Node1: /tmp/vagrant-chef/db03151bd4f28369e7a51fc0bda4fdda/cookbooks/cassandra/recipes/tarball.rb:132:in `from_file'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `instance_eval'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/mixin/from_file.rb:30:in `from_file'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/cookbook_version.rb:218:in `load_recipe'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:173:in `load_recipe'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/run_context.rb:96:in `load'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/client.rb:249:in `setup_run_context'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/client.rb:446:in `run'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:275:in `block in interval_run_chef_client'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `loop'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:264:in `interval_run_chef_client'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:242:in `run_application'
==> Node1: /opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
==> Node1: /opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
==> Node1: /usr/bin/chef-solo:52:in `load'
==> Node1: /usr/bin/chef-solo:52:in `<main>'
==> Node1: [2015-03-28T14:33:52+00:00] ERROR: undefined method `each' for nil:NilClass
==> Node1: [2015-03-28T14:33:52+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

Looks like the recipe is missing the `node['cassandra']['log_config_files']` attribute.
I guess that this merge can be the cause:
https://github.com/michaelklishin/cassandra-chef-cookbook/commit/9a2a4929f2cc9d4439e9abe377852002344a47b5#diff-25e5d4a4446ae12a0d6f1162b6160375

My Vagrantfile:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Cassandra Cluster Settings
server_count = 3
network = '10.0.1.'
first_ip = 10
cluster_name = 'Cassandra-Cluster'
# vars
servers = []
seeds = []
cassandra_tokens = []
# Generate server configs
(0..server_count-1).each do |i|
	name = 'Node' + (i + 1).to_s
	ip = network + (first_ip + i).to_s
	seeds << ip
	servers << {'name' => name,
						 'ip' => ip,
						 'initial_token' => 2**127 / server_count * i
	}
end
Vagrant.configure(2) do |config|
	# The most common configuration options are documented and commented below.
	# For a complete reference, please see the online documentation at
	# https://docs.vagrantup.com.

	# Every Vagrant development environment requires a box. You can search for
	# boxes at https://atlas.hashicorp.com/search.
	config.berkshelf.enabled = true
	config.omnibus.chef_version = :latest
	config.vbguest.auto_update = false
	servers.each do |server|
		config.vm.define server['name'] do |machine|
			machine.vm.box = "chef/centos-6.5"
			machine.vm.hostname = server['name']
			machine.vm.network :private_network, ip: server['ip']
			machine.vm.provider "virtualbox" do |v|
				v.name = cluster_name.gsub(/\s*/, '') + '-' + server['name']
			end

			machine.vm.provision :chef_solo do |chef|
				chef.log_level = :debug
				chef.add_recipe "apt"
				chef.add_recipe "java"
				chef.add_recipe "cassandra::tarball"
				chef.json = {
					:cassandra => {
						'cluster_name' => cluster_name,
						'initial_token' => server['initial_token'],
						'seeds' => seeds,
						'listen_address' => server['ip'],
						'rpc_address' => server['ip']
					},
					:java => {
						'install_flavor' => "oracle",
						'jdk_version' => "7",
						'oracle' => {
							'accept_oracle_download_terms' => true
						}
					}
				}
			end
		end
	end
end
```
My Berksfile:
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

site :opscode

cookbook 'apt'
cookbook 'java'
cookbook 'cassandra', git: 'https://github.com/michaelklishin/cassandra-chef-cookbook.git'
```
Any thought about how to solve it locally? Or should I fork, add the attribute, test and submit a pull request?

### PR DESCRIPTION
**Pull request by Restless-ET**
…default recipe instead of datastax one.

**Together with #190 and #191** I believe this will fix #184.
If all of them are accepted, please merge the other two PRs first and then if necessary I'll update this one.

Anyway, every PR can be merged independently while maintaining BC.

### CODE REVIEW

**Comment by michaelklishin** [comment]
Should we include `include_recipe "default"` explicitly?

**Comment by michaelklishin** [comment]
@Restless-ET this PR cannot be merged cleanly. Can you please look into the conflicts?

**Comment by michaelklishin** [comment]
Right, so this cannot be merged even after #190 and #191 were. Please look into the conflicts.

**Comment by Restless-ET** [comment]
Conflicts fixed. This should be good to go now.

BTW, the idea behind (this together with #190) is to always use the ```cassandra::default``` recipe on our roles/run_list and the new ```install_method``` attribute instead of explicitly using ```cassandra::datastax``` or ```cassandra::tarball``` recipes.

**Comment by michaelklishin** [comment]
@Restless-ET then we need to also update the docs

**Comment by Restless-ET** [comment]
@michaelklishin Docs updated.

**Pull request merged**
