### PR TITLE
Additional JVM tunable options

### PR DESCRIPTION
**Pull request by msilvey**
Adding some additional JVM tuning parameters.  The defaults are based on either JDK 8 defaults as per the results of 'java -XX:+PrintFlagsFinal' or pre-existing options in the cassandra-env template.

### CODE REVIEW

**Comment by msilvey** [comment]
Can anyone explain the intended goal of the rspec to match the processed output of the cassandra-env.sh template with a predefined config file?  Is it to have a predefined version of default values?  Some other purpose?

**Comment by michaelklishin** [comment]
@msilvey the idea is to render a template with a particular config and assert on what comes out.

**Comment by msilvey** [comment]
OK, I'll render a new cassandra-env.sh for the changes and reopen this.

**Comment by msilvey** [comment]
Updated with a new cassandra-env.sh test and rendered output.

**Comment by michaelklishin** [comment]
@msilvey please update change log and credit yourself.

**Pull request merged**
