### PR TITLE
Fix gc options

### PR DESCRIPTION
**Pull request by msilvey**
This is a resubmit of https://github.com/michaelklishin/cassandra-chef-cookbook/pull/236

Making the docs and config options line up properly.

### CODE REVIEW

**Comment by michaelklishin** [comment]
@vkhatri I'm travelling in the next couple of days, can you please take a look?

**Comment by vkhatri** [comment]
@michaelklishin Ack.

**Comment by vkhatri** [comment]
@msilvey Could you please re base the PR and include commit related to jvm fix? this will keep the commit history clean.

**Comment by michaelklishin** [comment]
I'm merging this because it looks sensible and has been in play for almost a month.

**Comment by msilvey** [comment]
thanks

**Pull request merged**
